### ISSUE TITLE
Adding filter

### ISSUE THREAD

**Issue by jdk-sal3** [51bitquant/multi_pairs_martingle_bot#1]
Suggestion: please add whitelist / blacklist / filter to remove unwanted (low volume) coin

**Comment by 51bitquant** [comment]
> Suggestion: please add whitelist / blacklist / filter to remove unwanted (low volume) coin

Excellent Idea, I will add the filters to the config.json file.

**Comment by 51bitquant** [comment]
Have finished this function.
