### ISSUE TITLE
你好，请问一下这个马丁格尔策略的止损是怎么设置的呢

### ISSUE THREAD

**Issue by liuyi123321** [51bitquant/multi_pairs_martingle_bot#3]
你好，我想请问一下您的马丁格尔策略的至顺是如何设置的，当已经加仓到最大次数了，价格仍然下跌，似乎spot_trader的start 中并没有这种情况的止损

**Comment by xhl1993** [comment]
没有止损

**Comment by 51bitquant** [comment]
> 你好，我想请问一下您的马丁格尔策略的至顺是如何设置的，当已经加仓到最大次数了，价格仍然下跌，似乎spot_trader的start 中并没有这种情况的止损

已经支持设置止损了。 编辑config.json文件，设置stop_loss_pct为一个大于零的值就可以了。0.2 就是20%的止损， 0.05，就是5%止损。

**Comment by liuyi123321** [comment]
好滴，谢谢啦
