### ISSUE TITLE
PytzUsageWarning

### ISSUE THREAD

**Issue by kuratkull** [51bitquant/multi_pairs_martingle_bot#4]
how can i fix this error

{'id': 1, 'signals': [{'pct': 0.005517104676324491, 'pct_4h': 0.018028263232711783, 'symbol': 'ETHUSDT', 'hour_turnover': 49728662.897455, 'signal': 0}], 'time': datetime.datetime(2022, 6, 24, 16, 34, 55, 17887)}

PytzUsageWarning: The zone attribute is specific to pytz's interface; please migrate to a new time zone provider. For more details on how to do so, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html 
  if obj.zone == 'local':

 PytzUsageWarning: The normalize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return self.timezone.normalize(dateval + difference), fieldnum

**Comment by 51bitquant** [comment]
update the dependencies to the newest version.

> pip install apscheduler==3.10.1
